### ISSUE TITLE
No content in application window at startup

### ISSUE THREAD

**Issue by mattsjo** [yoichiro/chromeos-filesystem-sftp#43] opened 2015-02-23 21:36 UTC
The accept and reject texts are shown briefly at startup as seen in one attached screenshot. After about one second the texts disappear as seen on the other screenshot.
![screenshot 2015-02-23 at 22 30 10](https://cloud.githubusercontent.com/assets/621933/6338064/5b362942-bbac-11e4-942b-8d6da313e947.png)
![screenshot 2015-02-23 at 22 29 52](https://cloud.githubusercontent.com/assets/621933/6338067/635697b0-bbac-11e4-9fa4-46bcbaa5e0de.png)

**Comment by yoichiro** [comment] 2015-02-23 23:51
@mattsjo Hmm... I can't understand the detail situation from the images above. Well, could you confirm the console output of the background context? You can see the output by opening the DevTools from the chrome://extensions page. I may know the cause of this issue from the output contents...

**Comment by mattsjo** [comment] 2015-02-24 20:10
Hi,
I can't see any output in the console but if I enter the Emulation tab and
emulate almost any device then the setup screen appears, more or less in
the correct size. The "Emulate screen resolution" must be checked.
If I manually set the resolution to 1920x1080 the setup screen can still be
seen...

I have a Samsung chromebook 2 with a 1920x1080 display.

Thanks for investigating my problem!

[image: Infogad bild 2]

2015-02-24 0:51 GMT+01:00 Yoichiro Tanaka <notifications@github.com>:

**Comment by mattsjo** [comment] 2015-02-24 20:23
Another strange thing.
When I entered some info into the setup page and clicked Mount then I
couldn't see the popup unless I unchecked "Emulate screen resolution".
I did manage to connect to my raspberry and can now see all files in the
file browser!

Thank you very much for this app!

2015-02-24 21:10 GMT+01:00 Mattias Sjögren <mattias.sjogren@gmail.com>:

**Comment by yoichiro** [comment] 2015-02-24 21:58
@mattsjo Hmm... I can't the option "Emulate screen resolution" on the screen setup panel in my Chromebook... But, looks good to me if you could solve this issue. I close this issue.

Thank you for the report!

**Closed by yoichiro** 2015-02-24 21:58 UTC
